[global_attributes]  # add your global attributes to this section of the file
    source = "example_generate_netcdf_file.py"
    Conventions = "CF-1.6"
    institution = "Colorado State University"
    title = "Example NetCDF file"
[groups]
    [groups.blah]
        [groups.blah.attributes]
            title = "This is the blah data"

        [groups.blah.dimensions]  # NetCDF variable dimensions

            [groups.blah.dimensions.time]
                long_name = "time"
                standard_name = "time"
                calendar = "standard"
                units = "hours since 1970-01-01"
                dtype = "int32"
                dat = "time"

            [groups.blah.dimensions.latitude]
                units = "degrees_north"
                long_name = "latitude coordinate"
                standard_name = "latitude"
                dtype = "float32"
                dat = "lat"

            [groups.blah.dimensions.longitude]
                long_name = "longitude coordinate"
                standard_name = "longitude"
                units = "degrees_east"
                dtype = "float32"
                dat = "lon"

        [groups.blah.variables]  # Variable section of the netCDF file

            [groups.blah.variables.pwat]
                long_name = "precipitable water in mass per unit area; forecast"
                standard_name = "atmosphere_mass_content_of_water_vapor"
                units = "kg m-2"
                dtype = "float64"
                dim = [ "time", "latitude", "longitude",]
